### ISSUE TITLE
nets module can't be imported

### ISSUE THREAD

**Issue by T-Troll** [arthurdjn/nets#1]
Python 3.6.7-1~18.04, Ubuntu.
Then try to import nets, i recieve this error:
```
Python 3.6.9 (default, Jul 17 2020, 12:50:27)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nets
ERROR:root:Cannot import CuPy. No module named 'cupy'
ERROR:root:CuPy not imported. No module named 'cupy'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../.local/lib/python3.6/site-packages/nets/__init__.py", line 5, in <module>
    from nets.autograd import Hook, Parameter
  File "/home/.../.local/lib/python3.6/site-packages/nets/autograd/__init__.py", line 3, in <module>
    from .functional import *
  File "/home/.../.local/lib/python3.6/site-packages/nets/autograd/functional.py", line 15, in <module>
    import nets.autograd.function as fc
AttributeError: module 'nets' has no attribute 'autograd'
>>>
```

Did CUDA and CuPy in strict requrements? Host doesn't have it.

**Comment by arthurdjn** [comment]
Hello, I apologize for my late feedback. I tried the package with your configuration and faced the same issue. I fixed the line that required ``cupy``,  and pushed the changes to [PyPi](https://pypi.org/project/nets/). You can now download the latest version (0.0.3.1).

```
pip install nets==0.0.3.1
```

Hope this answer will still help you !
